/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trandpl.gui;

import java.awt.Desktop;
import java.io.File;
import java.sql.SQLException;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import trandpl.dao.ParticipantsDAO;
import trandpl.dao.ResultsDAO;
import trandpl.pojo.CurrentUser;
import trandpl.pojo.ParticipantPojo;


public class HrViewParticipantFrame extends javax.swing.JFrame {
     private ParticipantPojo obj=null;
    private String emailId;
    private String jobId;
    private String jobTitle;
    public HrViewParticipantFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public HrViewParticipantFrame(String emailId,String jobId,String jobTitle) {
       this();
       this.emailId=emailId;
       this.jobId=jobId;
       this.jobTitle=jobTitle;
       loadData();
       
    }
    private void loadData(){
       try{
            obj=ParticipantsDAO.getPrDetails(this.emailId);
            
           lblPrId.setText(obj.getId());
           txtName.setText(obj.getName());
           txtEmail.setText(obj.getUserId());
           txtNo.setText(obj.getPhone());
           txtSkill1.setText(obj.getSkills());
           txtQualification.setText(obj.getQualification());
           
       } 
       catch(Exception ex)
         {
             JOptionPane.showMessageDialog(null,"DB Error","Error",JOptionPane.ERROR_MESSAGE);
             ex.printStackTrace();
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrId = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtSkill1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQualification = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnResume = new javax.swing.JButton();
        btnSelectCandidate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 246, 254));
        jPanel1.setPreferredSize(new java.awt.Dimension(1016, 709));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/World-Map.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 996, 208));

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setText("Participant Id :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 245, -1, -1));

        lblPrId.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblPrId.setText("jLabel4");
        jPanel1.add(lblPrId, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 245, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 274, 409, 10));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(173, 192, 234));
        txtEmail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 400, 30));

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(173, 192, 234));
        txtName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 410, 30));

        txtNo.setEditable(false);
        txtNo.setBackground(new java.awt.Color(173, 192, 234));
        txtNo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtNo.setBorder(null);
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 410, 30));

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel5.setText("Mobile No. :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel6.setText("Name : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 378, -1, 50));

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel9.setText("Eamil : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 435, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 50));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 950, 10));

        txtSkill1.setEditable(false);
        txtSkill1.setBackground(new java.awt.Color(173, 192, 234));
        txtSkill1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtSkill1.setBorder(null);
        jPanel1.add(txtSkill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 548, 250, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 290, 50));

        txtQualification.setEditable(false);
        txtQualification.setBackground(new java.awt.Color(173, 192, 234));
        txtQualification.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtQualification.setBorder(null);
        jPanel1.add(txtQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 920, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, 300, 50));

        jLabel14.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel14.setText("Skills : ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, 50));

        jLabel16.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel16.setText("Qualification : ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, -1, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_4018958162.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, -1, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tg_image_915734271.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 630, 290, 50));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newimages/new/viewAllQualified.png"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 200, 170));

        btnResume.setText("View Resume ");
        btnResume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumeActionPerformed(evt);
            }
        });
        jPanel1.add(btnResume, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 180, 30));

        btnSelectCandidate.setText("Select Candidate ");
        btnSelectCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCandidateActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelectCandidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TIT/logo-only (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumeActionPerformed
         try{
             String path="D://Program Files//trandpl//Resumes//"+obj.getName()+"Resume.pdf";
             File file=new File(path);
             if(Desktop.isDesktopSupported())
             {
                 Desktop.getDesktop().open(file);
             }
             else{
                 JOptionPane.showMessageDialog(null,"Not Supported","Support ? ",JOptionPane.ERROR_MESSAGE);
             }
         }  
         catch(Exception ex)
         {
             ex.printStackTrace();
         }
    }//GEN-LAST:event_btnResumeActionPerformed

    private void btnSelectCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCandidateActionPerformed
       
       try{
              boolean flag=sendMail(this.obj);
              if(flag==false)
              {
                  JOptionPane.showMessageDialog(null,"Please check your internet Connection","Internet ?",JOptionPane.WARNING_MESSAGE);
                  return ;
              }
              else {
                   boolean result=ResultsDAO.changeStatus(obj.getId());
                   if(result==true)
                   {
                      JOptionPane.showMessageDialog(null,"Mail sent successfully","success",JOptionPane.INFORMATION_MESSAGE);
                      new HrViewTestResult().setVisible(true);
                      this.dispose(); 
                   }
                   else{
                      JOptionPane.showMessageDialog(null,"Error while changing status","Error",JOptionPane.ERROR_MESSAGE);
                   } 
              }
         }
       catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null,"DB Error ","Error",JOptionPane.ERROR_MESSAGE);
           ex.printStackTrace();
       }
        
    }//GEN-LAST:event_btnSelectCandidateActionPerformed
      private boolean sendMail(ParticipantPojo obj){
         final String username = "hmaywad9589@gmail.com";
         final String password = "nketfywfcgpclihg";
        // Step 1
        Properties prop = new Properties();
	prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "465");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.socketFactory.port", "465");
        prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        
        Authenticator myAuth=new MyAuthenticator(username,password);        
        Session session = Session.getInstance(prop,myAuth);                

        try {

            Message message = new MimeMessage(session);
            InternetAddress[]recipients=InternetAddress.parse(obj.getUserId());
            message.setRecipients(
                    Message.RecipientType.TO,
                    recipients
            );
            message.setSubject("Interview Invitation From"+CurrentUser.getId());
            message.setText("Hello "+obj.getName()+",\nWarm Welcome From "+CurrentUser.getName()+"\n"
                +"You are qualified our first technical round\n"
                +"Job id : "+this.jobId+"\n"
                +"Job Title : "+this.jobTitle+"\n"
                +"\nYour Interview will be taken by "+CurrentUser.getName()+"\n"
                +"Interview Schedule and meeting link will be shared soon \n"
                +"\nWarm Regards"
                +"\n"+CurrentUser.getId());
              
            Transport.send(message);  
            System.out.println("Mail Sent Successfully!");
           return true;
        }
       
        catch (MessagingException e) {
            e.printStackTrace();
            return false;
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrViewParticipantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrViewParticipantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrViewParticipantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrViewParticipantFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrViewParticipantFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResume;
    private javax.swing.JButton btnSelectCandidate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPrId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JTextField txtSkill1;
    // End of variables declaration//GEN-END:variables
}
